#!/usr/bin/env sh

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding
yabai -m config                             \
    external_bar                "main:0:0"  \
    top_padding                 10          \
    bottom_padding              10          \
    left_padding                10          \
    right_padding               10          \
    window_gap                  10

# mouse
yabai -m config                             \
    mouse_follows_focus         off         \
    focus_follows_mouse         off         \
    mouse_modifier              fn          \
    mouse_action1               move        \
    mouse_action2               resize      \
    mouse_drop_action           swap

# certain windows should always float
yabai -m rule --add app="(Preferences|Install|Parallels)" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="Cisco Secure Client" manage=off
yabai -m rule --add app="Stats" manage=off

yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -e ".\"can-resize\"" || yabai -m window $YABAI_WINDOW_ID --toggle float' app="Microsoft Teams"
