#!/bin/bash

help() {
cat << EOF
Usage: $0 [--chip <chip>] [-w <warning>] [-c <critical>]
    --help          Show this message
    --chip <chip>   sensor chip
    -w <number>     warning threshold to become yellow
    -c <number>     critical threshold to become yellow
EOF
}

args=$(getopt -a -o c:w: --long chip:,help -- "$@")
if [[ $? -gt 0 ]]; then
  help
  exit 1
fi

# Main
set -euo pipefail

chip=""
t_crit=90
t_warn=70

eval set -- "${args}"
while :
do
  case $1 in
    --help) help; shift ;;
    --chip) chip=$2; shift 2 ;;
    -c)     t_crit=$2; shift 2 ;;
    -w)     t_warn=$2; shift 2 ;;
    --)     shift; break ;;
    *)
       echo "Unsupported option: $1"
       help
       exit 1
       ;;
  esac
done

temperature=$(sensors -u "$chip" | grep -oP 'temp1_input:\s+\K(\d+)')

# Print short_text, full_text
echo "$temperature°C"
echo "$temperature°C"

# Print class if needed
if [[ $temperature -gt $t_crit ]]; then
  echo "critical"
elif [[ $temperature -gt $t_warn ]]; then
  echo "warning"
fi
