
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [
  { chars = "\u0000", key = "Space", mods = "Control" },
]

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 0

[scrolling]
history = 40000
multiplier = 3

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/alacritty_dark.toml",
]
