[colors.bright]
black = "0x4b505b"
red = "0xd05858"
green = "0x608e32"
yellow = "0xbe7e05"
blue = "0x5079be"
magenta = "0xb05ccc"
cyan = "0x3a8b84"
white = "0xbac3cb"

[colors.normal]
black = "0x8790a0"
red = "0xd05858"
green = "0x608e32"
yellow = "0xbe7e05"
blue = "0x5079be"
magenta = "0xb05ccc"
cyan = "0x3a8b84"
white = "0xdde2e7"

[colors.primary]
background = "0xfafafa"
foreground = "0x4b505b"

[colors.cursor]
cursor = "0x4d4d4c"

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
