[colors.bright]
black = "0x8e908c"
blue = "0x969896"
cyan = "0xa3685a"
green = "0xe0e0e0"
magenta = "0x282a2e"
red = "0xf5871f"
white = "0x1d1f21"
yellow = "0xd6d6d6"

[colors.cursor]
cursor = "0x4d4d4c"

[colors.normal]
black = "0xffffff"
blue = "0x4271ae"
cyan = "0x3e999f"
green = "0x718c00"
magenta = "0x8959a8"
red = "0xc82829"
white = "0x4d4d4c"
yellow = "0xeab700"

[colors.primary]
background = "0xffffff"
foreground = "0x4d4d4c"

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
